### PR TITLE
Update parking_lot to 0.12

### PR DESCRIPTION
**Pull request by andrioni**
Small version bump. Checked the changelog and ran tests locally, and everything seems fine.

### CODE REVIEW

**Comment by yodaldevoid** [comment]
Is there a specific reason why we need to update `parking_lot`?

**Comment by Kroisse** [comment]
To update `parking_lot`, it allows us to avoid having two versions of the crate being built when used with other crates that use `parking_lot 0.12`. Although `ssh2` does not expose the type of `parking_lot` as an external interface, updating can still contribute to reducing compilation time and binary size even if we do not face [version-incompatibility hazards][1].

[1]: https://doc.rust-lang.org/cargo/reference/resolver.html#version-incompatibility-hazards

**Comment by yodaldevoid** [comment]
I did not realize we had multiple versions of `parking_lot` in our dependency graph.

It looks like your current PR has a merge conflict. If you do a quick rebase I'd be happy to merge it.

**Comment by yodaldevoid** [comment]
I have opened #299, which is just your commit rebased on master.

**Pull request closed without merging**
