### PR TITLE
make sure the test runs only on unix like OS's

### PR DESCRIPTION
**Pull request by twitzelbos**
- this should prevent windows tests from failing

### CODE REVIEW

**Comment by yodaldevoid** [comment]
I admittedly don't know this feature well, but is there any way to modify the test to be able to run on both Windows and *nix?

**Comment by twitzelbos** [comment]
It will be possible in windows as well, as soon as https://github.com/rust-lang/libs-team/issues/271 lands.

**Comment by twitzelbos** [comment]
PS: I also know why the MacOS action is going on forever.

**Comment by demosdemon** [comment]
Oops sorry. That was a clumsy mistake. I forgot that needed to be excluded for windows.

**Pull request merged**
