### PR TITLE
Use a larger buffer for readdir

### LINKED ISSUE #217: read_dir() doesn't work properly
Hello,
I found a bug in this library. I use it in a homemade backup program and I was surprised that in some folders there was missing files.
So, I investigate my code, and...finally think that the Sftp::read_dir is maybe buggy.
So, I check this, and, finally, the problem is here: (read_dir in File)
https://docs.rs/ssh2/0.9.1/src/ssh2/sftp.rs.html#577-614

Your buffer is on the size of 128 bytes. When I change this size to 4096 (just to try), all my files are seen in the folder.

I think I have understood the problem:
You have a 128 bytes buffer, when you got the "this is too small" error, you upgrade the buffer length.
But, when you got the file again, you got the next file (so you just skipped a file)
And, if this happen many times, you can got folders like mine where you see only 3 files of 24...

Workarround: Set a bigger buffer size.
But, I think there is maybe a better way to fix it, by asking libssh to send the same file name again, and not the next, maybe.
Or maybe there is possible to know in advance the good buffer size.
Or maybe 128bytes is really too small...

But, I let you fix this, because I'm not experienced with libssh in C...

When you push a fix, I can test on my computer to see if, in my test case this is fixed :) (Note: I use the crates.io version)

Thank you :)

### PR DESCRIPTION
**Pull request by sourcefrog**
The libssh2 C API skips entries if the buffer is not big enough, so the
previous strategy of retrying with a larger buffer on error will
actually cause some files to be skipped.

Fixes #217

### CODE REVIEW

**Comment by crone123** [comment]
Hello,
I think it will be better to let the user choose the buffer size, and put a default of something like 4096 bytes, to prevent allocating huge buffers.
I personally use a local fork of this lib for 1 year, with 4096 bytes as buffer, and there is no issue with this.
Remember that this buffer is only used to store the path of a file, so 64k is very huge, and will have a performance impact because of reallocating it multiple time.

By the way, it can be good to allocate this buffer one time, and never allocate again, because SSH in this lib doesn't support multiple calls at the same time it shouldn't be a problem.  (I have to create multiple instances for doing that without problems)
Because allocating 64k each time someone will just read a folder will have a huge performance impact. (and memory cost).

On a unix/linux filesystem, the maximum length for a path is 255 bytes, so 4096 is already huge but can happen if we mount a disk inside another path.

What did you think about that? 
Thank you :)

**Comment by sourcefrog** [comment]
Good point, thanks for replying. 

I'll reduce it to 4k, which should be plenty for any single filename+metadata?

I don't think there will be a performance problem:

There should only be one buffer in use at any point in time, at least per connection.

The underlying library is doing singlethreaded, non-pipelined (I think) network round trips to a remote machine, which is itself doing file IO. A small allocation should be very cheap by comparison.

The allocator should already be pretty good at repeatedly allocating a small buffer. I'm not sure there's a good case to hold on to it here, especially given the previous point. At any rate it seems it could be done separately from this fix.

**Comment by crone123** [comment]
Yeah, I think 4k should be enough, I never had any problem in 1 year (and millions files/folders) with this buffer size :)

**Comment by sourcefrog** [comment]
@alexcrichton can you take a look?

**Comment by sourcefrog** [comment]
Just to be a bit more precise

> On a unix/linux filesystem, the maximum length for a path is 255 bytes, so 4096 is already huge but can happen if we mount a disk inside another path.

Actually a _path_ can be up to 4kiB <https://serverfault.com/a/306726> it's only a single component that's limited to 255B. However readdir should only be returning single filenames so this seems fine.

**Comment by yodaldevoid** [comment]
This seems reasonable to me as a temporary hack around https://github.com/libssh2/libssh2/issues/714. That said, I'd rather change the inital capacity to 4086 due to the reasons you folks have found and keep the loop in tact. With this change, I'd like a note pointing to https://github.com/libssh2/libssh2/issues/714 to be added.

While keeping the loop, as pointed out by @harmic in #251, the capacity is not being increased in the loop correctly. If you could implement their fix for this capacity increase bug, it would be appreciated.

**Comment by sourcefrog** [comment]
Hi,

This PR currently has 4kiB. (I presume your "4086“ is a typo.)

I don't think there's any point in a loop because if we don't get it right on the first try, data will be lost. It's better to surface that with an error. It also seems unlikely that 4kiB wouldn't be enough to read a dir entry.

**Comment by harmic** [comment]
I noticed that bug with the way that buffer capacity is being increased also exists in [`readlink_op`](url) - ie. it does not actually resize the buffer. I guess that should be handled via another issue?

It might be good to at least leave the current loop code there but commented out, to make it easier to improve if/when libssh2 do fix the problem.

**Comment by sourcefrog** [comment]
Are you able to approve merges and make a new release? Otherwise we're just talking until Alex has time and energy to look at this, or until someone wants to maintain a fork. 

I can handle symlinks too, thanks for pointing that out. 

This does not seem like a case where a loop with a larger buffer would ever be necessary? The upper bound is knowable and reasonably to allocate up front.

**Comment by yodaldevoid** [comment]
I've included a version of the buffer increase in #262 as well as a bump in the vendored version of libssh2 to include a fix to the underlying issue. I cannot make releases the `libssh2-sys`, but I'll push those who can to do so shortly.

Thank you for your work on this issue.

**Comment by sourcefrog** [comment]
Thanks! Per https://github.com/alexcrichton/ssh2-rs/pull/245#issuecomment-1250553120 do we need to do an analogous change for readlink?

**Comment by yodaldevoid** [comment]
> Thanks! Per [#245 (comment)](https://github.com/alexcrichton/ssh2-rs/pull/245#issuecomment-1250553120) do we need to do an analogous change for readlink?

I believe that was addressed in https://github.com/alexcrichton/ssh2-rs/commit/b912f7e043425e89856db45c2f07d8ae9dd7c0af.

**Pull request closed without merging**
